### ISSUE TITLE
NPM now required?!?

### ISSUE THREAD

**Issue by hongkongkiwi** [ORESoftware/quicklock#13]
Hi there,

Suddenly Quicklock requires NPM in the latest version. Why is this? It is a bash script.

I'm using it in some dockers where npm is not available, is there any reason why this is needed?

**Comment by ORESoftware** [comment]
@hongkongkiwi will take a look at this tomorrow, it shouldn't require NPM. You should be able to install it with cURL without NPM.

Is there a specific error you're getting?

**Comment by ORESoftware** [comment]
Yeah, I see it now, when you run the curl install command, npm is invoked, let me investigate, weird

**Comment by hongkongkiwi** [comment]
See pull request #14 :-)

Just checks if NPM is installed first before running associated commands.

**Comment by hongkongkiwi** [comment]
Totally agree with you. I think best to keep npm dependency.

In my case, I didn't realise it required node.js at all. I was using an old version which didn't have the node dependency see pull request comment. #14 

I think it might be good to make that clear in the README and also to add some nice error handling incase npm or node is not installed. I really like the following one liner for that.
`command -v foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }`

**Comment by ORESoftware** [comment]
sounds good will ping you here when I publish a stable new version

**Comment by ORESoftware** [comment]
@hongkongkiwi  I created a new bash-only utility that is much better than this project. The new one is evented and once the lock is released, any askers will get notified. It's very nice and much simpler than this crap that I was writing last year. If you're interested let me know.

Although the `flock` utility seems to work (and notifies askers that are waiting):

```bash

(
flock -x 200

 echo 'a:111'
 sleep 2
 echo 'a:222'


) 200>"$temp_dir/a" &

(
flock -x 200

 echo 'b:111'
 sleep 2
 echo 'b:222'

) 200>"$temp_dir/a" &
```
